version: '3'
services:
  postgres:
    image: postgres:12.3
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_portal_db
    volumes:
      - ./init.sql:/docker-environment-initdb.d/init.sql